### ISSUE TITLE
Slimmer title bars for Mint-X [Feature Request]

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/sticky#19]
In keeping with the ideal of "to make it feel like a unified and cohesive desktop" with this particular application.  For those of us who still live in the world of the Mint-X themes, is there any way to include a setting to reduce the height of the title bars?  I do realize there needs to be room for the graphics but make them just a bit slimmer?  Trim the padding?  Include a smaller set of icons for Mint-X? The title bars just seem a bit out of proportion for a small note.

**Comment by collinss** [comment]
If anything, this should be filed against mint-x. Individual applications should not adapt to specific themes. If an app doesn't look right in a particular theme, it should almost always be fixed in the theme, not in the app.

That being said, there is nothing there that should change based on the theme this case. In fact, care is specifically taken to strip out any theme-specific styling to avoid the notes changing appearance based on theme. This is done for two reasons, and I think it is the right approach. The first is quite practical, and is reason enough on it's own imo. You see, the notes themselves are not meant to look like other windows and blend in, and so they really _shouldn't_ match the rest of the desktop exactly. The second is more technical, but still valid in it's own right. The problem with this one is that the notes have quite a bit of extra theming to them - certainly more than enough to ensure that it would be impossible to guarantee that the extra styling would fit in with every theme.

As for the height of the titlebar, I believe the limiting factor is usually the font size of the title itself (which changes based on the font selected in settings), so there's only so much flexibility right now (and believe me, it would look much worse if we didn't scale the title along with the text).
