### ISSUE TITLE
Why reinvent the wheel?

### ISSUE THREAD

**Issue by Sonophoto** [linuxmint/sticky#6]
I was asked to comment on this so I am. Why is Linux Mint reinventing yet another notes app? Seriously: What goal is being accomplished by duplicating effort when high quality liberated software is already available?

Note: (no pun) I have used "sticky note" apps for 2+ decades, they've been available on essentially all OSes all along. currently I use gnome's xpad, its fantastic - but maybe it is missing something I've never noticed...

**Comment by collinss** [comment]
Hi @Sonophoto I just tried out xpad, and I'm less than impressed. It's ugly, clunky to use, and has no options for formatting that I could see. In addition, anything I type is lost when I click 'close' - there doesn't seem to be any persistence at all. And the most egregious of all (at least from my perspective) is that I couldn't drag the notes to move them. Another point of annoyance for me is that each new note adds another entry to the window list, making this virtually unusable for more than 2-3 notes at a time.

I'm sure if you just need to jot something down for a second, it would be an acceptable tool, but if you want to keep track of information for any length of time, organize the notes into groups, add formatting, checklists, bullets, etc, or show/hide them from a single button, then xpad simply wont cut it. In fact, I haven't seen a single sticky note app that can do all of that except this one.

Putting all that aside, the point is not just to add yet another sticky notes app to the Linux ecosystem. Linux Mint is more than just a collection of packages. The goal is to make it feel like a unified and cohesive desktop, and that means software that fits in well, is easy to use, and is versatile enough that it suites a wide audience. If this app does end up being included in Mint, it will not be because it's the next new thing, or because it is developed by a member of the team, but because it best suites the needs of the distribution and it's users.

As for my own reasons for developing it in the first place, there wasn't a sticky notes app that felt comfortable to me and did everything I wanted it to. I suppose I could have chosen to contribute to one of the other projects, or even fork one of them. But by starting from scratch, I not only had the freedom to implement things according to my own vision, but I was able to build it from the beginning with the features I wanted in mind, rather than trying to add them ad-hock to an existing framework that wasn't designed for them. Even if this doesn't make it into Linux Mint (or even if no one else ever uses it), I'm glad I created it, and will continue to develop it because it fits my needs so much better than any other note taking app I've ever seen.

**Comment by Sonophoto** [comment]
My response would be that you did not read the instructions or bother configuring it to function as you wish. All of your claims are invalid by direct observation of a properly installed and appropriately configured xpad. persistence is automatic, written to disk. alt+left mouse drag moves all windows anyways and you can turn on the systems window decorations if you wish.

In your second paragraph you are wanting a simple display note in a toolbar to be a kanban board. Why not reinvent that?

In your third paragraph I would suggest that if LM has excess resources they should update the upstream for its packages more often than every one or two major version numbers. Things like that don't suit anyone, especially people trying to do work other than play around with OSes. Please, I'm not talking about oddballs, I'm talking about darktable, gimp, blender and several others. from two stable releases behind, to a major version and file format changes.

fourth: That is why there are 500 versions of Linux. I guess that is your main point really...

May your road be straight and the wind at your back.

**Comment by collinss** [comment]
> All of your claims are invalid by direct observation of a properly installed and appropriately configured xpad.

All I did was install the app from the official repository and try to use it. I shouldn't have to read a page and a half of documentation in order to use such a simple sticky note app. It's clearly not intuitive enough if I can't figure it out in 30 seconds.

> persistence is automatic, written to disk.

Ok, I did eventually figure out how to get old notes back, but that just goes back to my previous point - it's not intuitive, and very poorly designed.

> you are wanting a simple display note in a toolbar to be a kanban board.

No, a kanban board is a specific way of organizing notes, and that's not specifically what I'm describing. I can already organize my physical sticky notes however I want, so why shouldn't I be able to do so with my digital ones as well. This is especially important since Mint's current default note taking app (Gnote, which this app would potentially replace) has this functionality already, and many users rely on that.

> I would suggest that if LM has excess resources they should update the upstream for its packages more often than every one or two major version numbers.

Ok, first of all, it isn't LM itself that has "extra resources" as you put it. I never said that, and that simply isn't true. I am not a full time employee of Linux Mint. I chose to work on this project in my free time because it interested me. There was no expectation that it would become part of Linux Mint when I began, and my working on this project did not in any way take resources from something else (in fact, this project actually got me excited about contributing again after quite a while with little to no motivation). Second of all, the goal of Linux Mint is not to have cutting-edge software. Stability is just as important as new features to us. If you want cutting edge, you should probably look somewhere else (and by the way, 2 years is hardly an extreme case in the linux world). And third, Flatpak has mitigated this issue a lot, allowing software to be updated regularly as new versions come out, while the core set of packages stays stable. (btw, I checked and every program you mentioned has a flatpak available in the software manger).

> That is why there are 500 versions of Linux.

I've never understood why some people get upset when there are 20 different versions of the same type of app. The only way this could possibly hurt anyone is when someone can't find the good app for all the bad ones they see first, but I don't even really buy that because any app that is truly better than the others is going to be promoted far more, so it will tend to show up first in search results and blog posts. What is far more problematic (in my opinion) is when none of the options are very good, and that is what I aim to fix in this case with this app.

**Comment by Sonophoto** [comment]
First, all in good nature: and all statements other than statements of objective facts are entirely my (possibly worthless) opinion. ;-)

1. Yes, it is 1 1/2 screen of clearly written task focused documentation, no webpage, its builtin to the application. Press "F1" (in use for 30 plus years) and a single page pops up with a scrollbar. RTFM is also an old, very valid, tradition.

2. "Very poorly designed?" Provide substantive evidence other than subjective opinion. (I'll accept substantive evidence, cruft, messy X, messy C, etc.)

3. I over generalized. You make a clear and valid point.

4a. My misunderstanding came from this being in the September News and was presented as a Mint Project contributed by you and specifically requested "Feedback and bug reports are welcome..." https://blog.linuxmint.com/?p=3969.

4b. Understanding your second point I totally understand why you are doing it. I wrote an RPN calculator in OG Javascript and HTML 4.0. Why? (seriously lol) Because I was learning JS and HTML by doing something useful and I love stacks and statemachines. I get that. This is your baby, not LM's project.

4c. I'm not talking about stalking devs and alphas. I'm talking about the repo not being kept up to date when stable versions are released of high functioning software that is used by working professionals. Users are scientists, visual artists, illustrators, videographers, musicians, gamers, and soccer moms and grannies on facebook. You and I can build whatever we want from raw source in a terminal. No average linux user can do that. You said "The goal is to make it feel like a unified and cohesive desktop,..." OK. Darktable should be in the 3.x series, not 2.x IN the native repo, not the latest fad gimmick. 

4d. Yep, and they still aren't up to date. Look I just spend a few hours and build these things from scratch and wrap them up as app images, dump them in a private bin, simlink the binary and create a launcher from scratch - wasted time but I can do it no problem. I've gotten many people to try Linux over the years. They all go back to windows, they never fall in love with Linux because of the repository issue. The only nix users I've ever kept were on managed machines. Even a PhD physicist I got into Linux 16 years ago quit because he was frustrated over libraryitis, broken APM, code breaking updates. You cannot regress something that is never stable. He's on windows ten now because it just works and he is busy doing something other than dinking around with OSes and flakey software applications. He's doing physics.

5a. Parsimony. Occam's Razor (The Latin version)

5b. Again, I encourage you to move forward. I am glad you are encourage and motivated by this and I hope you understand my time spent in this discussion is given to you out of respect and gratitude for you as a developer of liberated software. 

I believe we gain more from honest criticism than empty praise.

**Comment by collinss** [comment]
> First, all in good nature: and all statements other than statements of objective facts are entirely my (possibly worthless) opinion.

I would hesitate to call anyone's opinion worthless, as opinion is a large part of how we view and interact with the world, but I would tend to agree with the sentiment, that much of what we've been discussing is a matter of opinion, and therefore not objective.

> Press "F1" (in use for 30 plus years) and a single page pops up with a scrollbar. RTFM is also an old, very valid, tradition.

Well, yes, and I could have found the help again without problem. (Though you'd be surprised how many people don't know a single keyboard shortcut these days - my wife would always right click to copy/paste until I taught her how to use the keyboard.) My point was that with something as simple as a sticky note app, it should be fairly straightforward to use and I shouldn't have to spend 2 minutes reading the manual to figure out how to use it (again, this is my personal opinion and not objective fact, though I would say that this is part of the philosophy that I and many others on the LM team go by when making design decisions.

> "Very poorly designed?" Provide substantive evidence other than subjective opinion. 

Ok, so I may have been in a little bit of a bad mood when I wrote that (for completely unrelated reasons), and was perhaps a bit overly critical. That being said, there are several points in that app that I would consider poor design, or design limitations at the very least:
* As I mentioned above, many people either do not know keyboard shortcuts, or simply prefer to use the mouse, but some of the features are only available through the keyboard (i.e. formatting such as bold/italics).
* As I mentioned in a previous comment, having a separate entry in the window list for every note makes this unusable if you have more than a couple of notes. After looking through the settings a bit more, I did see that there is an option to skip the taskbar, but that means it's much harder to get them back (unless maybe you have the tray icon enabled - which for some reason isn't showing up on my system).
* Not being able to just click and drag is a bit of an annoyance for me. Yes, I know you can do it by holding down alt, but that's something that's implemented by the window manager (so it's not guaranteed in all desktop environments - though I haven't actually tried it with other window managers). More importantly, using alt to move a window is something I've only used rarely so it's not part of my workflow (and like other keyboard shortcuts, it isn't something that most users are going to know about). You can also enable the window decorations in the settings for dragging, but that makes it look more ugly, and adds additional space that isn't used for anything else.
* There doesn't seem to be a way to close all of the notes at once. This may be possible from the tray icon, but since that isn't working for me, I can't really say.
* After closing all of the notes, opening the app gives me a blank note rather than restoring my existing notes (which is why I initially thought they weren't getting saved). Restoring existing notes feels clunky to me, and not at all intuitive.

> My misunderstanding came from this being in the September News and was presented as a Mint Project contributed by you

Ah yes, it was rather vague wasn't it. I can see how you might get confused. Though I am "on the team" there isn't an expectation that I do particular things. I'm basically free to work on whatever I want (there's no guarantee that what I do will get merged either, but it usually does). I try to help out where and when I can, but I'm not an employee, and it isn't my day job. In fact there are really only 2 individuals that do this full time, and only one of them handles things like the repositories, maintaining the websites, and other such administrative tasks.

> I wrote an RPN calculator in OG Javascript and HTML 4.0.

I see I'm not the only one who loves rpn... :)

> Darktable should be in the 3.x series, not 2.x IN the native repo, not the latest fad gimmick.

The flatpak version (from Flathub) is 3.2.1. As I said before, flatpak really helps with this situation. Having the same base for 2 years really takes a lot of burden off of the team (particularly the 2 full-timers), and frees us up to work on making the distro better, at the cost of not having cutting edge software. Flatpak largely mitigates that issue by allowing us to have the up-to-date software with all the benefits of staying on the same lts package base and avoid the frequent breakages that come with newer libraries and utilities.

> Even a PhD physicist I got into Linux 16 years ago quit because he was frustrated over libraryitis, broken APM, code breaking updates.

Yup, this is one of the biggest reasons we switched to an lts package base that we only change every 2 years. It was really annoying having things break on us every 6 months, and it really hurt productivity as well. I will note also that windows tends to have just as many breakages as linux, just not as many api breakages because many of their customers depend on older software.

> Parsimony. Occam's Razor (The Latin version)

By that same argument, you could say that we have too many movies, tv shows, etc, and maybe that's true too depending on your perspective, but my own opinion is that if even one person finds value in something then it shouldn't be considered "unnecessary plurality" unless the cost outweighs the value gained. Often the value of something goes beyond merely the use of that thing. For example, I've found that a failed venture can (and often does) lead to learning whose value is far greater than the product of that venture if it had succeeded. For that reason, I don't think we can say whether the multitude of similar software is "unnecessary plurality" or not, but I do believe the only ones who could really be hurt by the development of such software are the ones who created it.

**Comment by 5hirish** [comment]
@collinss Learnt about your project through LM blog. I am super excited about this project. Your following words resonated with me :

> Linux Mint is more than just a collection of packages. The goal is to make it feel like a unified and cohesive desktop, and that means software that fits in well, is easy to use, and is versatile enough that it suites a wide audience. If this app does end up being included in Mint, it will not be because it's the next new thing, or because it is developed by a member of the team, but because it best suites the needs of the distribution and it's users.

I have been an LM user since LM12 and I always wanted LM to feel like a unified and cohesive desktop. And I was really excited when the XApps started popping up!

I have been searching for simple sticky notes app that feels like it's wearing the skin of the OS so I settled for the sublime text editor instead. I usually will post code snippets or just some random stuff. Looking forward to it!

Best wishes!

**Comment by mas1701** [comment]
Sticky Notes does not sync data with Nextcloud and other sync services, Gnote did it well in Linux Mint 21.x. Now, after upgrading to 22.2, Gnote still works, but all sync options are greyed out despite sync extensions being enabled and a Nextcloud account is configured. This is a step backwards and  very frustrating.
