### ISSUE TITLE
Auto-linking of plain text

### ISSUE THREAD

**Issue by the0neWhoKnocks** [linuxmint/sticky#91]
I've noticed with notes that have multiple formatted links, if I want to type plain text between the links, the plain text is formatted as a link. If I try to copy some plain text and paste it in an area between links it's also formatted.
```
<formatted_link_1>

(type here -> results in link formatted text)

<formatted_link_2>
```

Is there a way to remove the link formatting via a keyboard shortcut? There didn't appear to be anything via the context-menu.

**Comment by collinss** [comment]
I've fixed the issue leading to your situation, and it will hopefully make it into a point release. Unfortunately, this will not fix your existing notes, so you'll probably have to cut and paste the affected lines once you have the updated version. I'm hesitant to add the ability to manually mark a link, as that will open a whole new can of worms that I've purposefully avoided. That being said, I wouldn't have a problem with an option to simply remove all link formatting from a selection of text, but I can pretty much guarantee that such a feature wouldn't land until at least the next major version (probably in June or July) because it would require new translatable text.

**Comment by the0neWhoKnocks** [comment]
Cool, glad it was another simple fix.

For future issues/fixes like this that would require user intervention to fix existing notes, I wonder if it'd be prudent to add an internal patching mechanism. Something as simple as checking the app's version, and if lower than X, apply patch.
In the case of this fix:
- Maybe save a backup of DB in case something happens
- Iterate existing notes
- Run parser
- Overwrite note content
- If a backup was created, notify the user of it's location in case something happened

Just a suggestion. Thanks for your attention on this issue.

**Comment by the0neWhoKnocks** [comment]
Fair enough, thanks for the reply.
